name: circular_splash_transition
description: A simple page transition with a circle that opens from the middle of the screen until it completely fills it and then closes back to the middle with the page altered.
  Uma simples transição de tela com um circulo que se abre do meio da tela até preencher completamente ela e, depois, se fecha de volta para o meio apresentando a tela alterada.

version: 0.1.3
author: joao_uefrom <joao.fernandesds26@gmail.com>
homepage: https://github.com/joao-uefrom/circular_splash_transition

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: