name: circular_splash_transition
description: A simple custom page transition.
version: 0.1.1
author: joao_uefrom <joao.fernandesds26@gmail.com>
homepage: https://github.com/joao-uefrom/circular_splash_transition

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: